
apiVersion: v1
kind: Service
metadata:
  name: myappbalance
spec:
  selector:
    app: myapp
  ports: 
  - protocol: TCP
    port: 80 
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels: 
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: zakgregory/myapp
        ports:
        - containerPort: 5000
