---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports: 
  - protocol: TCP
    port: 80 
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels: 
    app: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: zakgregory/practical-project-service1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports: 
  - protocol: TCP
    port: 5001
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels: 
    app: service2
spec:
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: zakgregory/practical-project-service2
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports: 
  - protocol: TCP
    port: 5002
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels: 
    app: service3
spec:
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: zakgregory/practical-project-service3
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service4
spec:
  selector:
    app: service4
  ports: 
  - protocol: TCP
    port: 5003
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
  labels: 
    app: service4
spec:
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: service4
        image: zakgregory/practical-project-service4
        ports:
        - containerPort: 5003
